take 2

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -96,7 +96,15 @@ jobs:
     if: ${{ always() }}
     steps:
       - name: Check test matrix results
-        run: if [ ${{failure()}} ]; then exit 1; else exit 0; fi
+        run: |
+          echo "Overall result of 'unit_tests' job: ${{ needs.unit_tests.result }}"
+          if [[ "${{ needs.unit_tests.result }}" != "success" ]]; then
+            echo " One or more unit tests failed or were cancelled."
+            exit 1
+          else
+            echo "All unit tests passed."
+            exit 0
+          fi
 
 
   integ_tests:
