Update ci_tests.yml

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -180,12 +180,12 @@ jobs:
           output_file=$(mktemp)
 
           # Run terraform apply, redirect both stdout and stderr to the file
-          if ! terraform apply -var-file=../google-services.json -auto-approve  2> "$output_file" ; then
-            cat "$output_file" >&2
+          if ! terraform apply -var-file=../google-services.json -auto-approve  > "$output_file" 2>&1  ; then
+            cat "$output_file"
             if cat "$output_file" | grep -q "index already exists"; then
-              echo "===================================================================================" >&2
-              echo -e "\e[93m\e[1mTerraform apply failed due to index already exists; We can safely ignore this error.\e[0m" >&2
-              echo "===================================================================================" >&2
+              echo "==================================================================================="
+              echo -e "\e[93m\e[1mTerraform apply failed due to index already exists; We can safely ignore this error.\e[0m" 
+              echo "==================================================================================="
             fi
             exit 1
           fi
