Update ci_tests.yml

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -178,17 +178,18 @@ jobs:
 
           # Define a temporary file to store the output
           output_file=$(mktemp)
-          
+
           # Run terraform apply, redirect both stdout and stderr to the file
           if ! terraform apply -var-file=../google-services.json -auto-approve  > "$output_file" 2>&1 ; then
             cat "$output_file" >&2
             if cat "$output_file" | grep -q "index already exists"; then
-              echo "==================================================================================="
-              echo -e "\e[93m\e[1mERROR: Terraform apply failed due to index already exists; We can safely ignore this error.\e[0m"
+              echo "===================================================================================" >&2
+              echo -e "\e[93m\e[1mTerraform apply failed due to index already exists; We can safely ignore this error.\e[0m" >&2
+              echo "===================================================================================" >&2
             fi
             exit 1
           fi
-          
+
           # Clean up the temporary file
           rm -f "$output_file"
         continue-on-error: true
