Update ci_tests.yml

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -121,40 +121,6 @@ jobs:
         with:
           credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
       - uses: google-github-actions/setup-gcloud@v0
-      
-      # create composite indexes with Terraform
-      - name: Setup Terraform 
-        if: contains(matrix.module, ':firebase-firestore')
-        uses: hashicorp/setup-terraform@v2
-      - name: Terraform Init
-        if: contains(matrix.module, ':firebase-firestore')
-        run: |
-          cd firebase-firestore
-          terraform init
-        continue-on-error: true
-      - name: Terraform Apply
-        if: github.event_name == 'pull_request' && contains(matrix.module, ':firebase-firestore')
-        run: |
-          cd firebase-firestore
-
-          # Define a temporary file to store the output
-          output_file=$(mktemp)
-          
-          # Run terraform apply, redirect both stdout and stderr to the file
-          if ! terraform apply -var-file=../google-services.json -auto-approve  > "$output_file" 2>&1 ; then
-            echo "$output_file" >&2
-            if cat "$output_file" | grep -q "index already exists"; then
-              echo "============================================================================="
-              echo -e "\e[93m\e[1mERROR: Terraform apply failed due to index already exists; We can safely ignore this error.\e[0m"
-              echo "============================================================================="
-            else
-              echo "ERROR: terraform apply failed" >&2
-            fi
-            exit 1
-          fi
-          # Clean up the temporary file
-          rm -f "$output_file"
-        continue-on-error: true
       - name: ${{ matrix.module }} Integ Tests
         env:
           FIREBASE_CI: 1
@@ -196,6 +162,39 @@ jobs:
         with:
           credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
       - uses: google-github-actions/setup-gcloud@v0
+            
+      # create composite indexes with Terraform
+      - name: Setup Terraform 
+        if: contains(matrix.module, ':firebase-firestore')
+        uses: hashicorp/setup-terraform@v2
+      - name: Terraform Init
+        if: contains(matrix.module, ':firebase-firestore')
+        run: |
+          cd firebase-firestore
+          terraform init
+        continue-on-error: true
+      - name: Terraform Apply
+        if: github.event_name == 'pull_request' && contains(matrix.module, ':firebase-firestore')
+        run: |
+          cd firebase-firestore
+
+          # Define a temporary file to store the output
+          output_file=$(mktemp)
+          
+          # Run terraform apply, redirect both stdout and stderr to the file
+          if ! terraform apply -var-file=../google-services.json -auto-approve  > "$output_file" 2>&1 ; then
+            cat "$output_file" >&2
+            if cat "$output_file" | grep -q "index already exists"; then
+              echo "==================================================================================="
+              echo e "\e[93m\e[1m-Terraform apply failed due to index already exists; We can safely ignore this error.\e[0m"
+            fi
+            exit 1
+          fi
+          
+          # Clean up the temporary file
+          rm -f "$output_file"
+        continue-on-error: true
+
       - name: Firestore Named DB Integ Tests
         env:
           FIREBASE_CI: 1
