cleanup

diff --git a/.github/workflows/dataconnect.yml b/.github/workflows/dataconnect.yml
--- a/.github/workflows/dataconnect.yml
+++ b/.github/workflows/dataconnect.yml
@@ -186,10 +186,12 @@ jobs:
         working-directory: firebase-dataconnect/emulator
         run: |
           set -xveuo pipefail
+          docker compose up -d --quiet-pull
 
-          docker compose up -d
-
-          set +xv
+      - name: Wait for Postgres Server to be Ready
+        working-directory: firebase-dataconnect/emulator
+        run: |
+          set -euo pipefail
 
           function print_docker_compose_status {
             docker compose ps --format=json
@@ -199,18 +201,18 @@ jobs:
             print_docker_compose_status | jq -e 'select(.Service == "postgres") | .Status'
           }
 
-          echo "Waiting for postgres service to appear to be healthy..."
           postgres_health_check_number=0
           while : ; do
             postgres_health_check_number=$((postgres_health_check_number + 1))
-            status="$(print_postgres_status)"
-            echo "postgres health check ${postgres_health_check_number} status: ${status}"
-            if [[ ${status} =~ "healthy" ]] ; then
-              echo "Postgres server appears to be healthy after ${postgres_health_check_number} seconds"
+            postgres_service_status="$(print_postgres_status)"
+            echo "Postgres service health check ${postgres_health_check_number}: ${postgres_service_status}"
+
+            if [[ ${postgres_service_status} =~ "healthy" ]] ; then
+              echo "Postgres service appears to be healthy after ${postgres_health_check_number} seconds"
               break
             elif [[ ${postgres_health_check_number} == 30 ]] ; then
               print_docker_compose_status
-              echo "ERROR: postgres service does not appear to be healthy after ${postgres_health_check_number} seconds" >&2
+              echo "ERROR: Postgres service does not appear to be healthy after ${postgres_health_check_number} seconds" >&2
               exit 1
             fi
 
