dataconnect.yml: add job to comment on an issue

diff --git a/.github/workflows/dataconnect.yml b/.github/workflows/dataconnect.yml
--- a/.github/workflows/dataconnect.yml
+++ b/.github/workflows/dataconnect.yml
@@ -51,6 +51,10 @@ jobs:
           - 5432:5432
 
     steps:
+      - run: |
+          echo "FORCED FAILURE gxppygj343"
+          exit 1
+
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           show-progress: false
@@ -259,3 +263,24 @@ jobs:
       - uses: docker://rhysd/actionlint:1.7.7
         with:
           args: -color /github/workspace/.github/workflows/dataconnect.yml
+
+  email-notification:
+    needs: [integration-test, actionlint-dataconnect-yml]
+    if: true || github.event_name == 'schedule'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Post Comment on Issue #6857
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -euo pipefail
+
+          cat >message.txt <<EOF
+          Result of workflow ${{ github.workflow }} at ${{ github.ref }}: ${{ job.status }}
+          ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
+          job=${{ github.job }} run_id=${{ github.run_id }} run_number=${{ github.run_number }} run_attempt=${{ github.run_attempt }} 
+          EOF
+
+          echo "Posting comment on GitHub Issue: https://github.com/firebase/firebase-android-sdk/issues/6857:"
+          cat message.txt
+          gh issue comment 6857 --body-file message.txt
