dataconnect.yml fixup

diff --git a/.github/workflows/dataconnect.yml b/.github/workflows/dataconnect.yml
--- a/.github/workflows/dataconnect.yml
+++ b/.github/workflows/dataconnect.yml
@@ -100,8 +100,11 @@ jobs:
 
       - name: Enable KVM Group Permissions for Android Emulator
         run: |
-          ./firebase-dataconnect/ci.zsh \
-          kvm_setup
+          set -euo pipefail
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
+            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
 
       - name: Restore AVD Cache
         uses: actions/cache/restore@d4323d4df104b026a6aa633fdb11d772146be0bf # 4.2.2
@@ -135,23 +138,42 @@ jobs:
             ~/.android/adb*
           key: avd-cache-zhdsn586je-api${{ env.FDC_ANDROID_EMULATOR_API_LEVEL }}-${{ github.run_id }}
 
-      - name: Start Firebase Emulators
+      - name: Data Connect Emulator Start
+        id: data-connect-emulator
         run: |
-          ./firebase-dataconnect/ci.zsh \
-          start_firebase_emulators \
-          -firebase_command '${{ env.FDC_FIREBASE_COMMAND }}' \
-          -postgres_connection_url 'postgresql://postgres:password@127.0.0.1:5432?sslmode=disable' \
-          -log_file firebase.emulators.log \
-          -enable_debug_logs ${{ runner.debug || '0' }}
+          set -euo pipefail
+          set -xv
+
+          echo 'emulator.postgresConnectionUrl=postgresql://postgres:password@127.0.0.1:5432?sslmode=disable' > firebase-dataconnect/dataconnect.local.properties
+
+          ./gradlew \
+            ${{ (inputs.gradleInfoLog && '--info') || '' }} \
+            :firebase-dataconnect:connectors:runDebugDataConnectEmulator \
+            >firebase.emulator.dataconnect.log 2>&1 &
+
+          echo "FIREBASE_DATA_CONNECT_EMULATOR_PID=$!" >> "$GITHUB_ENV"
+
+      - name: Firebase Auth Emulator Start
+        id: firebase-auth-emulator
+        run: |
+          set -euo pipefail
+          set -xv
+
+          cd firebase-dataconnect/emulator
+          ${{ env.FDC_FIREBASE_COMMAND }} emulators:start --only=auth >firebase.emulator.auth.log 2>&1 &
+
+          echo "FIREBASE_AUTH_EMULATOR_PID=$!" >> "$GITHUB_ENV"
 
       - name: Logcat Log Capture Start
         id: logcat-capture
         continue-on-error: true
         run: |
-          ./firebase-dataconnect/ci.zsh \
-          start_logcat_capture \
-          -adb_command "$ANDROID_HOME/platform-tools/adb" \
-          -log_file logcat.log
+          set -euo pipefail
+          set -xv
+
+          "$ANDROID_HOME/platform-tools/adb" logcat >logcat.log 2>&1 &
+
+          echo "LOGCAT_PID=$!" >> "$GITHUB_ENV"
 
       - name: Gradle connectedCheck
         id: connectedCheck
@@ -185,10 +207,11 @@ jobs:
           compression-level: 9
 
       - name: Verify "Gradle connectedCheck" Step Was Successful
+        if: steps.connectedCheck.outcome != 'success'
         run: |
-          ./firebase-dataconnect/ci.zsh \
-          verify_connected_check_success \
-          -connected_check_step_outcome '${{ steps.connectedCheck.outcome }}'
+          set -euo pipefail
+          echo 'Failing because the outcome of the "Gradle connectedCheck" step ("${{ steps.connectedCheck.outcome }}") was not successful'
+          exit 1
 
   # Check this yml file with "actionlint": https://github.com/rhysd/actionlint
   # To run actionlint yourself, run `brew install actionlint` followed by
@@ -212,17 +235,12 @@ jobs:
       issues: write
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          show-progress: false
-          sparse-checkout: 'firebase-dataconnect/ci.zsh'
-
       - name: Post Comment on Issue
         #if: github.event_name == 'schedule'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          set -eu
+          set -euo pipefail
 
           if [[ '${{ github.event_name }}' == 'schedule' ]] ; then
             readonly github_notification_issue=6857
@@ -231,14 +249,12 @@ jobs:
             readonly github_notification_issue=6863
           fi
 
-          ./firebase-dataconnect/ci.zsh \
-          send_notifications \
-          -github_notification_issue $github_notification_issue \
-          -github_workflow_name '${{ github.workflow }}' \
-          -github_repository '${{ github.repository }}' \
-          -job_status '${{ job.status }}' \
-          -git_commit_hash '${{ github.sha }}' \
-          -run_url '${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}' \
-          -run_id '${{ github.run_id }}' \
-          -run_number '${{ github.run_number }}' \
-          -run_attempt '${{ github.run_attempt }}'
+          cat >message.txt <<EOF
+          Result of workflow ${{ github.workflow }} at ${{ github.ref }}: ${{ job.status }}
+          ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
+          job=${{ github.job }} run_id=${{ github.run_id }} run_number=${{ github.run_number }} run_attempt=${{ github.run_attempt }}
+          EOF
+
+          echo "Posting comment on GitHub Issue: https://github.com/firebase/firebase-android-sdk/issues/$github_notification_issue:"
+          cat message.txt
+          gh issue comment $github_notification_issue --body-file message.txt -R ${{ github.repository }}
