dataconnect.yaml: improve readability of the output of the "tool versions" step

diff --git a/.github/workflows/dataconnect.yml b/.github/workflows/dataconnect.yml
--- a/.github/workflows/dataconnect.yml
+++ b/.github/workflows/dataconnect.yml
@@ -84,16 +84,22 @@ jobs:
       - name: tool versions
         continue-on-error: true
         run: |
-          set +e -v
-          uname -a
-          which java
-          java -version
-          which javac
-          javac -version
-          which node
-          node --version
-          ${{ env.FDC_FIREBASE_COMMAND }} --version
-          ./gradlew --version
+          function run_cmd {
+            echo "==============================================================================="
+            echo "Running Command: $*"
+            ("$@" 2>&1) || echo "WARNING: command failed with non-zero exit code $?: $*"
+            echo
+          }
+
+          run_cmd uname -a
+          run_cmd which java
+          run_cmd java -version
+          run_cmd which javac
+          run_cmd javac -version
+          run_cmd which node
+          run_cmd node --version
+          run_cmd ${{ env.FDC_FIREBASE_COMMAND }} --version
+          run_cmd ./gradlew --version
 
       - name: Gradle assembleDebugAndroidTest
         run: |
